CONFIG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('entity/', include('apps.entity.urls')),
    path('health/', include('apps.health.urls')),
    path('inventory/', include('apps.cashier.urls')),
    path('auth/', include('apps.usersys.urls')),
    path('', include('apps.dashboard.urls')),
    path('',include('apps.reports.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/entity/urls.py
from django.urls import path
from apps.entity.views.client.views import ClientViews
from apps.entity.views.provider.views import ProviderViews
from apps.entity.views.pet.views import PetViews, detail_pet

app_name = 'entity'

urlpatterns = [
    # CRUD CLIENTS URL
    path('listado_clientes/', ClientViews.as_view(), name = 'clients'),
    # CRUD PROVIDERS URL
    path('listado_proveedores/', ProviderViews.as_view(), name = 'providers'),
    # CRUD PETS URL
    path('listado_mascotas/', PetViews.as_view(), name = 'pets'),
    # DETAIL PET URL
    path('listado_mascotas/detail/<int:id>/', detail_pet, name = 'detail_pet'),

]

apps/entity/models.py
from django.db import models
from CONFIG.settings import MEDIA_URL
from datetime import datetime, date
from django.forms import model_to_dict
from apps.entity.choices import type_client, gender_choices, gender_pet, species_pet

import secrets

# Create your models here.

def my_urlsecret():
    return secrets.token_urlsafe(32)

class Estado(models.Model):
    status = models.BooleanField(default=True, verbose_name='Estado')
    urlsecret = models.SlugField(max_length=50, default=my_urlsecret , null=True , blank=True)
    next_visit = models.DateField(default=date.today, verbose_name='Proxima visita', null=True , blank=True)
    status_notify = models.BooleanField(default=True, verbose_name='Notificador')

    class Meta:
        abstract=True

class Client(Estado):
    dni = models.CharField(max_length=8, verbose_name='Cedula', unique=True)
    gender = models.CharField(max_length=15, choices=gender_choices )
    type_name = models.CharField(max_length=10, choices=type_client, default = 'V-')
    first_name = models.CharField(verbose_name="Nombres", max_length=40)
    last_name = models.CharField(verbose_name="Apellidos", max_length=40)
    address = models.CharField(verbose_name="Direccion Habitacional", max_length=100, null=True, blank=True)
    mobile = models.CharField(verbose_name="Número de Celular",  max_length=11 , null = True, blank=True)
    tlf = models.CharField(verbose_name="Número de Telefonico", max_length=11 , null = True, blank=True)
    Email = models.EmailField(verbose_name= "Correo Electronico", null = True, blank=True)
    fechaa = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de edición")

    def __str__(self):
        return (self.dni + ' : ' + self.first_name)

    def get_gender_display(self):
        if self.gender:
            return '{}'.format(self.gender)
    

    def toJSON(self):
        item = model_to_dict(self)
        item['gender'] = self.get_gender_display()
        return item

    class Meta:
        verbose_name_plural = 'Clientes'
        verbose_name = 'Cliente'
        ordering = ['id']

class Provider(Estado):
    name = models.CharField(verbose_name="Nombres", max_length=40)
    rif = models.CharField(max_length =100, unique =True, verbose_name='RIF', null = True, blank=True)
    mobile = models.CharField(verbose_name="Número de Celular",  max_length=11 , null = True, blank=True)
    tlf = models.CharField(verbose_name="Número de Telefonico", max_length=11 , null = True, blank=True)
    Email = models.EmailField(verbose_name= "Correo Electronico", null = True, blank=True)
    date = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de edición")

    def __str__(self):
        return (self.name)

    def toJSON(self):
        item = model_to_dict(self)
        return item

    class Meta:
        verbose_name_plural = 'Proveedores'
        verbose_name = 'Proveedor'
        ordering = ['id']

class Pet(Estado):
    name = models.CharField(max_length = 50, verbose_name='Nombre')
    date_nac = models.DateField(auto_now=False, auto_now_add=False, verbose_name='Fecha de Nacimiento')
    gender = models.CharField(max_length = 20, choices=gender_pet, default='Hembra')
    race = models.CharField(max_length = 50, verbose_name='Raza')
    weight = models.FloatField(max_length = 10, verbose_name='Peso', default=0)
    specie = models.CharField(max_length = 50, choices=species_pet, default='Gato')
    date_up = models.DateField(auto_now=False, verbose_name='Fecha visita')
    substitute = models.CharField(max_length = 150, verbose_name='Suplente', null = True, blank=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='Propietario')

    def __str__(self):
        return (self.name)


    def toJSON(self):
        item = model_to_dict(self)
        item['client'] = {'id':self.client.id, 'dni': self.client.dni}
        return item

    class Meta:
        verbose_name_plural = 'Mascotas'
        verbose_name = 'Mascota'
        ordering = ['id']   
    
    

apps/entity/forms.py
from django.forms import ModelForm, ModelChoiceField
from apps.entity.models import Client, Provider, Pet
from apps.cashier.models import VaccineDay, ChildProduct

class ClientForm(ModelForm):

    class Meta:
        model = Client
        fields = '__all__'

        

class ProviderForm(ModelForm):

    class Meta:
        model = Provider
        fields = '__all__'

class PetForm(ModelForm):

    class Meta:
        model = Pet
        fields = '__all__'

class VaccineDayForm(ModelForm):
    product = ModelChoiceField(queryset=ChildProduct.objects.filter(stock__gt=0).order_by('-id'))

    class Meta:
        model = VaccineDay
        fields = '__all__'

apps/entity/views/client/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, Http404
from django.http import JsonResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from datetime import datetime
from django.contrib.auth.models import User, Permission

from apps.entity.forms import ClientForm
from apps.entity.models import Client, Pet

from apps.entity.mixins import Perms_Check

# CRUD CLIENTS URL
class ClientViews(Perms_Check, TemplateView):
    template_name = 'client/clients.html'
    permission_required = 'entity.view_client'

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for i in Client.objects.all():
                    if i.status == True:
                        i.status = '<span class="badge badge-success btn-colores">Activado</span>'
                    else:
                        i.status = '<span class="badge badge-dark">Desactivado</span>'
                    data.append(i.toJSON())
            
            elif action == 'add':
                perms = ('entity.add_client',)
                if request.user.has_perms(perms):
                    clien = Client()
                    clien.type_name = request.POST.get('type_name')
                    clien.dni = request.POST.get('dni')
                    clien.first_name = request.POST.get('first_name')
                    clien.last_name = request.POST.get('last_name')
                    clien.gender = request.POST.get('gender')
                    clien.address = request.POST.get('address')
                    clien.Email = request.POST.get('Email')
                    clien.mobile = request.POST.get('mobile')
                    clien.tlf = request.POST.get('tlf')
                    clien.status = 'status' in request.POST
                    clien.save()
                    user = User.objects.create_user(clien.dni, clien.Email, clien.dni)
                    permission = Permission.objects.get(codename='view_clientuser')
                    user.user_permissions.add(permission)
                    print(user)
                    user.save()
                else:
                    data['error'] = 'No tiene permisos para registrar un cliente'
            
            elif action == 'edit':
                perms = ('entity.change_client',)
                if request.user.has_perms(perms):
                    clien = Client.objects.get(pk=request.POST['id'])
                    user = User.objects.get(username=clien.dni)
                    clien.type_name = request.POST.get('type_name')
                    clien.dni = request.POST.get('dni')
                    user.username = clien.dni
                    user.set_password(clien.dni)
                    user.save()
                    clien.first_name = request.POST.get('first_name')
                    clien.last_name = request.POST.get('last_name')
                    clien.gender = request.POST.get('gender')
                    clien.address = request.POST.get('address')
                    clien.Email = request.POST.get('Email')
                    clien.mobile = request.POST.get('mobile')
                    clien.tlf = request.POST.get('tlf')
                    clien.status = 'status' in request.POST
                    clien.save()

                else:
                    data['error'] = 'No tiene permisos para editar un cliente'      

            elif action == 'delete':
                perms = ('entity.delete_client',)
                if request.user.has_perms(perms):
                    clien = Client.objects.get(pk=request.POST['id'])
                    clien.delete()
                else:
                    data['error'] = 'No tiene permisos para eliminar un cliente'

            elif action == 'detail':
                data = []
                for i in Pet.objects.filter(client_id=request.POST['id']):
                    item = i.toJSON()
                    item['date_nac'] = i.date_nac.strftime("%d-%m-%Y")
                    data.append(item)


            elif action == 'btn-estado':
                perms = ('entity.change_client',)
                if request.user.has_perms(perms):
                    clien = Client.objects.get(pk=request.POST['id'])
                    if clien.status:
                        clien.status = False
                        clien.save()
                    else:
                        clien.status = True
                        clien.save()
                else:
                    data['error'] = 'No tiene permisos para editar un cliente'  

            else:
                data['error'] = 'Ha ocurrido un error'           

        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'SISVET | Listado de Clientes'
        context['sub_titulo'] = 'Listado de Clientes'
        context['navegacion'] = 'Clientes'
        context['form'] = ClientForm()
        context['list_url'] = reverse_lazy('entity:clients')
        return context

apps/entity/views/pet/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, Http404
from django.http import JsonResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from datetime import datetime

from apps.entity.forms import PetForm
from apps.entity.models import Pet, Client
from apps.health.models import Consultation, Parasite, Vaccine

from apps.entity.mixins import Perms_Check

# CRUD PETS URL
class PetViews(Perms_Check, TemplateView):
    template_name = 'pet/pets.html'
    permission_required = 'entity.view_pet'

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for i in Pet.objects.all():
                    if i.status == True:
                        i.status = '<span class="badge badge-success btn-colores">Activado</span>'
                    else:
                        i.status = '<span class="badge badge-dark">Desactivado</span>'
                    data.append(i.toJSON())
            
            elif action == 'add':
                perms = ('entity.add_pet',)
                if request.user.has_perms(perms):
                    pet = Pet()
                    pet.name = request.POST.get('name')
                    pet.date_nac = request.POST.get('date_nac')
                    pet.gender = request.POST.get('gender')
                    pet.race = request.POST.get('race')
                    pet.weight = request.POST.get('weight')
                    pet.specie = request.POST.get('specie')
                    pet.date_up = request.POST.get('date_up')
                    pet.substitute = request.POST.get('substitute')
                    pet.client = Client.objects.get(pk = request.POST.get('client'))
                    pet.status = 'status' in request.POST
                    pet.save()
                else:
                    data['error'] = 'No tiene permisos para registrar una mascota'
            
            elif action == 'edit':
                perms = ('entity.change_pet',)
                if request.user.has_perms(perms):
                    pet = Pet.objects.get(pk=request.POST['id'])
                    pet.name = request.POST.get('name')
                    pet.date_nac = request.POST.get('date_nac')
                    pet.gender = request.POST.get('gender')
                    pet.race = request.POST.get('race')
                    pet.weight = request.POST.get('weight')
                    pet.specie = request.POST.get('specie')
                    pet.date_up = request.POST.get('date_up')
                    pet.substitute = request.POST.get('substitute')
                    pet.client = Client.objects.get(pk=request.POST.get('client'))
                    pet.status = 'status' in request.POST
                    pet.save()
                else:
                    data['error'] = 'No tiene permisos para editar una mascota'      

            elif action == 'delete':
                perms = ('entity.delete_pet',)
                if request.user.has_perms(perms):
                    pet = Pet.objects.get(pk=request.POST['id'])            
                    pet.delete()
                else:
                    data['error'] = 'No tiene permisos para eliminar una mascota'
            
            elif action == 'btn-estado':
                perms = ('entity.change_pet',)
                if request.user.has_perms(perms):
                    pet = Pet.objects.get(pk=request.POST['id'])
                    if pet.status:
                        pet.status = False
                        pet.save()
                    else:
                        pet.status = True
                        pet.save()
                else:
                    data['error'] = 'No tiene permisos para editar una mascota'  

            else:
                data['error'] = 'Ha ocurrido un error'           

        except Exception as e:
            data['error'] = str(e)
            print(data)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'SISVET | Listado de Mascotas'
        context['sub_titulo'] = 'Listado de Mascotas'
        context['navegacion'] = 'Mascotas'
        context['form'] = PetForm()
        context['list_url'] = reverse_lazy('entity:pets')
        return context


def detail_pet(request, id):
    template_name = 'pet/detail_pet.html'
    context = {}

    if id:
        pet = Pet.objects.filter(pk = id).first()
        consult = Consultation.objects.filter(pet_id = id).order_by('-id')[:15]
        parasite = Parasite.objects.filter(pet_id = id).order_by('-id')[:15]
        vaccine = Vaccine.objects.filter(pet_id = id).order_by('-id')[:15]

        context = {
            'pet': pet,
            'consult': consult,
            'parasite': parasite,
            'vaccine': vaccine,
        }

    else:
        context = {
            'prod': 'No hay datos',
            'stock': 'No hay datos'
        }

    return render(request, template_name, context)

apps/entity/templates/pet/pets.html
{% extends "list.html" %}
{% load static %}
{% load widget_tweaks %}
{% block head_list %}
  <script src="{% static 'pet/list.js' %}"> </script>
{% endblock %}
 
{% block add_element %}
<a href="#" class="btn btn-colores btn-add"><i class="fas fa-plus-square"></i></a>
{% endblock add_element %}
 
{% block t_body %}
    <tr>
        <th scope="col" style="width: 5%;">id</th>
        <th scope="col" style="width: 10%;">Nombre</th>
        <th scope="col" style="width: 10%;">Nacimiento</th>
        <th scope="col" style="width: 10%;">Sexo</th>
        <th scope="col" style="width: 5%;">Peso</th>
        <th scope="col" style="width: 8%;">Especie</th>
        <th scope="col" style="width: 10%;">Cliente</th>
        <th scope="col" style="width: 5%;">Estado</th>
        <th scope="col" style="width: 15%;">Opciones</th>
    </tr>
{% endblock t_body %}

{% block modal %}
<!-- Modal -->
<div class="modal fade" id="ModalNew" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <form method="POST" action="">
    {% csrf_token %}
    <input type="hidden" name="action" value="add" id="status">
    <input type="hidden" name="id" id="id" value="0">

    <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header color-nav">
            <h5 class="modal-title" id="exampleModalLabel"></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="container-fluid">
                <div class="card-body">
  
                  <div class="form-group">
                    <div class="row">
                      <div class="col">
                        <label for="id_client">Cliente <span class="text-danger" title="Campo Obligatorio">*</span></label>
                        {{ form.client|add_class:'form-control'|attr:'name:client'|add_class:'select2'|attr:'style:width:100%'}}
                      </div>
                      <div class="col">
                        <label for="id_name">Nombre <span class="text-danger" title="Campo Obligatorio">*</span></label>
                        {{ form.name|add_class:'form-control'|attr:'name:name'|attr:'placeholder:Introduzca el Nombre'|attr:'autocomplete:off'|attr:'maxlength:50' }}
                      </div>


                    </div>
                  </div>

                  <div class="form-group">
                    <div class="row">

                      <div class="col">
                        <label for="id_gender">Genero <span class="text-danger" title="Campo Obligatorio">*</span></label>
                        {{ form.gender|add_class:'form-control'|attr:'name:gender'}}
                      </div>
                      <div class="col">
                        <label for="id_weight">Peso <span class="text-danger" title="Campo Obligatorio">*</span></label>
                        {{ form.weight|add_class:'form-control'|attr:'name:weight'|attr:'placeholder:Direccion'}}
                      </div>
                      <div class="col">
                        <label for="id_specie">Especie <span class="text-danger" title="Campo Obligatorio">*</span></label>
                        {{ form.specie|add_class:'form-control'|attr:'name:specie'}}
                      </div>


                    </div>                      
                  </div>

                  <div class="form-group">
                    <div class="row">

                      <div class="col">
                        <label for="id_race">Raza <span class="text-danger" title="Campo Obligatorio">*</span></label>
                        {{ form.race|add_class:'form-control'|attr:'name:race'|attr:'placeholder:Raza'|attr:'pattern:[a-zA-Z ]+$'|attr:'maxlength:30'}}
                      </div>

                      <div class="col">
                        <label for="id_substitute">Suplente</label>
                        {{ form.substitute|add_class:'form-control'|attr:'name:substitute'|attr:'placeholder:Introduzca el Suplente'|attr:'autocomplete:off'|attr:'maxlength:50'|attr:'pattern:[a-zA-Z ]+$' }}
                      </div>

                    </div>
                  </div>

                  <div class="form-group">
                    <div class="row">

                      <div class="col">
                        <label for="id_date_nac">F_Nacimiento <span class="text-danger" title="Campo Obligatorio">*</span></label>
                        {{ form.date_nac|add_class:'form-control'|attr:'name:date_nac'|attr:'type:date'}}
                      </div>
                      <div class="col">
                        <label for="id_date_up">F_Visita <span class="text-danger" title="Campo Obligatorio">*</span></label>
                        {{ form.date_up|add_class:'form-control'|attr:'name:date_up'|attr:'type:date'}}
                      </div>

                    </div>
                  </div>
            
                  <div class="custom-control custom-switch custom-switch-on-success custom-switch-off-white">
                      {{ form.status|add_class:'custom-control-input'|attr:'name:status'|add_class:'status'}}
                      <label class="custom-control-label" for="id_status" >Estado <span class="text-danger" title="Campo Obligatorio">*</span></label>
                  </div>
                </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-dark" data-dismiss="modal">Cancelar</button>
            <button type="submit" class="btn btn-success btn-colores">Guardar</button>
          </div>
        </div>
      </div>
  </form>
</div>
<div class="modal fade" id="Modal_Detail" style="display: none" aria-hidden="true">
</div>
{% endblock modal %}