CONFIG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('entity/', include('apps.entity.urls')),
    path('health/', include('apps.health.urls')),
    path('inventory/', include('apps.cashier.urls')),
    path('auth/', include('apps.usersys.urls')),
    path('', include('apps.dashboard.urls')),
    path('',include('apps.reports.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/health/urls.py
from django.urls import path
from apps.health.views.consultas.views import ConsultaViews
from apps.health.views.desparacitacion.views import DesparacitacionViews 
from apps.health.views.vacunacion.views import VacunaViews
from apps.health.views.vaccine.views import VaccineDayViews, Create_VaccineDay, Edit_VaccineDay

app_name = 'health'

urlpatterns = [
    path("consultas/", ConsultaViews.as_view(), name="consultas"),
    path("desparacitacion/", DesparacitacionViews.as_view(), name="desparacitacion"),
    path("vacunacion/", VacunaViews.as_view(), name="vacunas"),
    # LIST, DETAIL AND DELETE VACCINE DAY
    path('listado_jornada_vacunacion/', VaccineDayViews.as_view(), name='vaccinedays'),
    # CREATE VACCINE DAY
    path('registrar_jornada_vacunacion/', Create_VaccineDay.as_view(), name='add_vaccineday'),
    # EDIT VACCINE DAY
    path('editar_jornada_vacunacion/<int:pk>/', Edit_VaccineDay.as_view(), name='edit_vaccineday'),
]

apps/reports/urls.py
from django.urls import path
from .views import PetsReports, VaccineReports, ParasiteReports, MenuHealth,MenuCashier, VentasReports, ConsultaReports
from .views import ConsultasReports, ProductosReports, ComprasReports, VentasDetalleReports, CompraDetalleReports, Report_RangeDate
from .views import Report_RangeDateVenta, Report_RangeDateCompra
from .views import ConsultaDetalleReports, VacunaDetalleReports, DespaDetalleReports

app_name = 'reports'

urlpatterns = [
    #MODULO HEALTH
    path("reports/pets/", PetsReports, name="report_pet"),
    path("reports/vaccine/", VaccineReports, name="report_vaccine"),
    path("reports/parasite/", ParasiteReports, name="report_parasite"),
    path("reports/consultation/<int:id>/", ConsultaReports, name="report_consultation"),
    path("reports/consultation/", ConsultasReports, name="report_consultas"),
    # MENU
    path("menu/reportes/medica/", MenuHealth.as_view(), name="menu_health"),
    path("menu/reportes/movimientos/", MenuCashier.as_view(), name="menu_cashier"),
    #MODULO CASHIER
    path("reports/ventas/", VentasReports, name="report_ventas"),
    path("reports/ventas/<int:id>/", VentasDetalleReports, name="report_ventasDetalle"),
    path("reports/compras/", ComprasReports, name="report_compras"),
    path("reports/compras/<int:id>/", CompraDetalleReports, name="report_CompraDetalle"),
    path("reports/productos/", ProductosReports, name="report_productos"),
    # REPORTES DINAMICOS
    path("reports_dinamic/<str:date1>/<str:date2>", Report_RangeDate, name="report_rangoConsulta"),
    path("reports_dinamic/venta/<str:date1>/<str:date2>", Report_RangeDateVenta, name="report_rangoVenta"),
    path("reports_dinamic/compra/<str:date1>/<str:date2>", Report_RangeDateCompra, name="report_rangoVenta"),

    # REPORTES DETALLES SECCION MEDICA
    path("reports/consultation/detalle/<int:id>/", ConsultaDetalleReports, name="report_consultationD"),
    path("reports/vacunacion/detalle/<int:id>/", VacunaDetalleReports, name="report_vaccinateD"),
    path("reports/desparasitacion/detalle/<int:id>/", DespaDetalleReports, name="report_desparasitationD"),
]

apps/reports/models.py
from django.db import models

# Create your models here.

apps/health/forms.py
from django.forms import ModelForm
from apps.health.models import Consultation, Vaccine, Parasite

class ConsultaForm(ModelForm):

    class Meta:
        model = Consultation
        fields = '__all__'

class DesparacitacionForm(ModelForm):

    class Meta:
        model = Parasite
        fields = '__all__'

class VacunaForm(ModelForm):

    class Meta:
        model = Vaccine
        fields = '__all__'

apps/health/views/consultas/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, Http404
from django.http import JsonResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from datetime import datetime, date, time, timedelta
from django.contrib.auth.models import User, Permission

from apps.health.forms import ConsultaForm
from apps.health.models import Consultation
from apps.entity.models import Pet
from apps.entity.mixins import Perms_Check

# CRUD CLIENTS URL
class ConsultaViews(Perms_Check, TemplateView):
    template_name = 'consultas/consultas.html'
    permission_required = 'health.view_consultation'

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for i in Consultation.objects.all():
                    if i.status == True:
                        i.status = '<span class="badge badge-success btn-colores">Activado</span>'
                    else:
                        i.status = '<span class="badge badge-dark">Desactivado</span>'
                    data.append(i.toJSON())
            
            elif action == 'add':
                perms = ('health.add_consultation',)
                if request.user.has_perms(perms):
                    consul = Consultation()
                    consul.motive = request.POST.get('motive')
                    consul.symptom = request.POST.get('symptom')
                    consul.temperature = request.POST.get('temperature')
                    consul.total = request.POST.get('total')
                    consul.date_c = request.POST.get('date_c')
                    consul.date_u = request.POST.get('date_u')
                    consul.diag_pre = request.POST.get('diag_pre')
                    consul.diag_def = request.POST.get('diag_def')
                    consul.fre_car = request.POST.get('fre_car')
                    consul.fre_res = request.POST.get('fre_res')
                    consul.examination = request.POST.get('examination')
                    consul.pet = Pet.objects.get(pk = request.POST.get('pet'))
                    consul.status = 'status' in request.POST
                    consul.save()
                    
                else:
                    data['error'] = 'No tiene permisos para registrar una consulta'
            
            elif action == 'edit':
                perms = ('health.change_consultation',)
                if request.user.has_perms(perms):
                    consul = Consultation.objects.get(pk=request.POST['id'])
                    consul.motive = request.POST.get('motive')
                    consul.symptom = request.POST.get('symptom')
                    consul.temperature = request.POST.get('temperature')
                    consul.total = request.POST.get('total')
                    consul.date_c = request.POST.get('date_c')
                    consul.date_u = request.POST.get('date_u')
                    consul.diag_pre = request.POST.get('diag_pre')
                    consul.diag_def = request.POST.get('diag_def')
                    consul.fre_car = request.POST.get('fre_car')
                    consul.fre_res = request.POST.get('fre_res')
                    consul.examination = request.POST.get('examination')
                    consul.pet = Pet.objects.get(pk=request.POST.get('pet'))
                    consul.status = 'status' in request.POST
                    consul.save()

                else:
                    data['error'] = 'No tiene permisos para editar una consulta'      

            elif action == 'delete':
                perms = ('health.delete_consultation',)
                if request.user.has_perms(perms):
                    consul = Consultation.objects.get(pk=request.POST['id'])            
                    consul.delete()
                else:
                    data['error'] = 'No tiene permisos para eliminar una consulta'

            else:
                data['error'] = 'Ha ocurrido un error'           

        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'SISVET | Listado de Consultas'
        context['sub_titulo'] = 'Listado de Consultas'
        context['navegacion'] = 'Consultas'
        context['form'] = ConsultaForm()
        context['list_url'] = reverse_lazy('health:consultas')
        return context

apps/health/views/consultation/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, Http404
from django.http import JsonResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from datetime import datetime

from apps.health.forms import ConsultForm
from apps.health.models import Consultation

from apps.entity.mixins import Perms_Check

# CRUD PETS URL
class ConsultViews(Perms_Check, TemplateView):
    template_name = 'consultation/consultations.html'
    permission_required = 'health.view_consultation'

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for i in Consultation.objects.filter(status = True ):
                    if i.status == True:
                        i.status = '<span class="badge badge-success btn-colores">Activado</span>'
                    else:
                        i.status = '<span class="badge badge-dark">Desactivado</span>'
                    data.append(i.toJSON())

            elif action == 'add':
                perms = ('health.add_consultation',)
                if request.user.has_perms(perms):
                    consul = Consultation()
                    consul.motive = request.POST.get('motive')
                    consul.symptom = request.POST.get('symptom')
                    consul.temperature = request.POST.get('temperature')
                    consul.total = request.POST.get('total')
                    consul.diag_pre = request.POST.get('diag_pre')
                    consul.diag_def = request.POST.get('diag_def')
                    consul.fre_car = request.POST.get('fre_car')
                    consul.fre_res = request.POST.get('fre_res')
                    consul.examination = request.POST.get('examination')
                    consul.pet = request.POST.get('pet')
                    consul.save()
                else:
                    data['error'] = 'No tiene permisos para registrar una Consulta'

            elif action == 'edit':
                perms = ('cashier.change_product',)
                if request.user.has_perms(perms):
                    pro = Consultation.objects.get(pk=request.POST['id'])
                    pro.name = request.POST.get('name')
                    pro.stock = request.POST.get('stock')
                    pro.price_buy = request.POST.get('price_buy')
                    pro.price_sale = request.POST.get('price_sale')
                    pro.date_conquered = request.POST.get('date_conquered')
                    pro.profit = request.POST.get('profit')
                    pro.num_sales = request.POST.get('num_sales')
                    pro.type_stock = request.POST.get('type_stock')
                    pro.quantity = request.POST.get('quantity')
                    pro.status = 'status' in request.POST
                    pro.save()
                else:
                    data['error'] = 'No tiene permisos para editar una mascota'      

            elif action == 'delete':
                perms = ('cashier.delete_product',)
                if request.user.has_perms(perms):
                    pro = Consultation.objects.get(pk=request.POST['id'])            
                    pro.delete()
                else:
                    data['error'] = 'No tiene permisos para eliminar una mascota'
            
            elif action == 'btn-estado':
                perms = ('cashier.change_product',)
                if request.user.has_perms(perms):
                    pro = Consultation.objects.get(pk=request.POST['id'])
                    if pro.status:
                        pro.status = False
                        pro.save()
                    else:
                        pro.status = True
                        pro.save()
                else:
                    data['error'] = 'No tiene permisos para editar una mascota'  

            else:
                data['error'] = 'Ha ocurrido un error'           

        except Exception as e:
            data['error'] = str(e)
            print(data)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'SISVET | Listado de Consultas'
        context['sub_titulo'] = 'Listado de Consultas'
        context['navegacion'] = 'Consultas'
        context['form'] = ConsultForm()
        context['list_url'] = reverse_lazy('health:consultations')
        return context

apps/reports/templates/health/consultas_reports.html
<!DOCTYPE html>
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<style>
    .head {
        text-align: center;
        text-transform: uppercase;
        font-size: 13px;
        font-weight: 600;
        margin-bottom: 3rem;
    }

    #invoice thead tr th {
        text-align: left;
        border-bottom: 1px solid black;
        border-top: 1px solid black;
        padding-top: 4px;
    }

    #invoice thead tr {
        margin-bottom: 0;
        padding-bottom: 0;
    }

    #invoice tbody tr {
        padding: 0;
    }

    .cosa{
        width: 100%;
        margin: 10px;
        border-top: black;
    }

    #invoice tbody tr td {
        text-align: left;
        border-bottom: 1px solid rgb(183, 183, 183);
        padding-top: 4px;
    }

</style>
<body>
<p class="head">
    <b style="font-size: 20px;">LEGOAGRO</b> <br>
</p>
<p>
    <b>FECHA DEL REPORTE:  {{ today|date:"d-m-Y" }}</b> <br>
    <b>Reporte de todas las consultas</b> <br>
</p>
<table id="invoice">
    <thead>
        <tr>
            <th class="cosa">Mascota</th>
            <th class="cosa">Motivo</th>
            <th class="cosa">Sintomas</th>
            <th class="cosa">Temperatura</th>
            <th class="cosa">Fre. Res.</th>
            <th class="cosa">Fre. Card.</th>
            <th class="cosa">Examenes</th>
            <th class="cosa">Diag. Def.</th>
        </tr>
    </thead>
    <tbody>
    {% for x in obj %}
        <tr>
            <td class="cosa">{{ x.pet.name }}</td>
            <td class="cosa">{{ x.motive }}</td>
            <td class="cosa">{{ x.symptom }}</td>
            <td class="cosa">{{ x.temperature }}</td>
            <td class="cosa">{{ x.fre_res }}</td>
            <td class="cosa">{{ x.fre_car }}</td>
            <td class="cosa">{{ x.examination }}</td>
            <td class="cosa">{{ x.diag_def }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>

apps/reports/templates/health/menu_cashier.html
{% extends "base.html" %}
{% load static %}
{% block tittle %}
<title>SISVET | Menu Reportes</title>
{% endblock tittle %}
{% block pluginscss %}
   <link rel="stylesheet" href="{% static 'lib/plugins/daterangepicker/daterangepicker.css' %}">
{% endblock pluginscss %}

{% block contenido %}

<div class="content">
    <h2 class="ml-2">Reportes Generales sección Movimientos</h2>
<div class="row mt-4">
    <div class="col-lg-3 col-6">
      <!-- small box -->
      <div class="small-box bg-info">
        <div class="inner">
          <h4 class="text-center">Ventas</h4>
        </div>
        <div class="icon">
          <i class="ion ion-bag"></i>
        </div>
        <a href="{% url 'reports:report_ventas' %}" class="small-box-footer">Descargar <i class="fas fa-arrow-circle-right"></i></a>
      </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
      <!-- small box -->
      <div class="small-box bg-success">
        <div class="inner">
          <h4 class="text-center">Compras</h4>
        </div>
        <div class="icon">
          <i class="ion ion-bag"></i>
        </div>
        <a href="{% url 'reports:report_compras' %}" class="small-box-footer">Descargar <i class="fas fa-arrow-circle-right"></i></a>
      </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
      <!-- small box -->
      <div class="small-box bg-warning">
        <div class="inner">
          <h4 class="text-center">Productos</h4>
        </div>
        <div class="icon">
          <i class="ion ion-bag"></i>
        </div>
        <a href="{% url 'reports:report_productos' %}" class="small-box-footer">Descargar <i class="fas fa-arrow-circle-right"></i></a>
      </div>
    </div>
    <!-- ./col -->
    <div class="col-md-6">
      <div class="card card-primary">
          <div class="card-header">
              <h3 class="card-title">Reportes de ventas por rango de fecha</h3>
          </div>
          <div class="card-body">
              <!-- Date -->
              <div class="form-group">
                  <label>Rango de Fecha:</label>
                  <div class="input-group date" data-target-input="nearest">
                      <input type="text" name="date1" id="date1" class="form-control pull-right">
                      <div class="input-group-append" >
                          <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                      </div>
                  </div>
              </div>
          </div>
          <div class="modal-footer">
              <button type="submit"  id="btn-print" class="btn btn-primary">Generar</button>
            </div>
          <!-- /.card-body -->
          
      </div>
      
      <!-- /.card -->
  </div>

  <div class="col-md-6">
    <div class="card card-success">
        <div class="card-header">
            <h3 class="card-title">Reportes de compras por rango de fecha</h3>
        </div>
        <div class="card-body">
            <!-- Date -->
            <div class="form-group">
                <label>Rango de Fecha:</label>
                <div class="input-group date" data-target-input="nearest">
                    <input type="text" name="date2" id="date2" class="form-control pull-right">
                    <div class="input-group-append" >
                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit"  id="btn-print2" class="btn btn-primary">Generar</button>
          </div>
        <!-- /.card-body -->
        
    </div>
    
    <!-- /.card -->
</div>
</div>
</div>
{% endblock contenido %}
{% block pluginsjs %}
<script>

    function Change() {
        var input1 = document.getElementById('date1').value;
        var input2 = document.getElementById('date2').value;

        lista_fecha = input1.split(' ');
        date1 = lista_fecha[0];
        date2 = lista_fecha[2];
        separador1 = date1.split('-');
        separador2 = date2.split('-');
        date1 = separador1[2] + '-' + separador1[1] + '-' + separador1[0];
        date2 = separador2[2] + '-' + separador2[1] + '-' + separador2[0];

        lista_fecha2 = input2.split(' ');
        date3 = lista_fecha2[0];
        date4 = lista_fecha2[2];
        separador3 = date3.split('-');
        separador4 = date4.split('-');
        date3 = separador3[2] + '-' + separador3[1] + '-' + separador3[0];
        date4 = separador4[2] + '-' + separador4[1] + '-' + separador4[0];

        $("#btn-print").click(function (e){
            e.preventDefault();
            var f1, f2;
            f1= date1;
            f2= date2;
            var url = "/reports_dinamic/venta/" + f1 + "/" + f2;
            window.open(url);
        });
        $("#btn-print2").click(function (e){
            e.preventDefault();
            var f3, f4;
            f3= date3;
            f4= date4;
            var url = "/reports_dinamic/compra/" + f3 + "/" + f4;
            window.open(url);
        });

    }

    $('#date1, #date2').change(function(){
        Change();
    });

    $(document).ready(function () {

        $('input[name="date1"]').daterangepicker({
            "locale": {
                "format": "DD-MM-YYYY",
                "separator": " - ",
                "applyLabel": "Aplicar",
                "cancelLabel": "Cancelar",
                "fromLabel": "De",
                "toLabel": "a",
                "customRangeLabel": "Custom",
                "daysOfWeek": [
                    "Do",
                    "Lu",
                    "Ma",
                    "Mi",
                    "Ju",
                    "Vi",
                    "Sa"
                ],
                "monthNames": [
                    "Enero",
                    "Febrero",
                    "Marzo",
                    "Abril",
                    "Mayo",
                    "Junio",
                    "Julio",
                    "Agosto",
                    "Septiembre",
                    "Octubre",
                    "Noviembre",
                    "Deciembre"
                ],
                "firstDay": 1
            }
        });
    });
    $(document).ready(function () {

$('input[name="date2"]').daterangepicker({
    "locale": {
        "format": "DD-MM-YYYY",
        "separator": " - ",
        "applyLabel": "Aplicar",
        "cancelLabel": "Cancelar",
        "fromLabel": "De",
        "toLabel": "a",
        "customRangeLabel": "Custom",
        "daysOfWeek": [
            "Do",
            "Lu",
            "Ma",
            "Mi",
            "Ju",
            "Vi",
            "Sa"
        ],
        "monthNames": [
            "Enero",
            "Febrero",
            "Marzo",
            "Abril",
            "Mayo",
            "Junio",
            "Julio",
            "Agosto",
            "Septiembre",
            "Octubre",
            "Noviembre",
            "Deciembre"
        ],
        "firstDay": 1
    }
});
});
</script>

<script src="{% static 'lib/plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'lib/plugins/daterangepicker/daterangepicker.js' %}"></script>
{% endblock pluginsjs %}

apps/reports/templates/health/menu_health.html
{% extends "base.html" %}
{% load static %}
{% block tittle %}
<title>SISVET | Menu Reportes</title>
{% endblock tittle %}
{% block pluginscss %}
   <link rel="stylesheet" href="{% static 'lib/plugins/daterangepicker/daterangepicker.css' %}">
{% endblock pluginscss %}
{% block contenido %}

<div class="content">
    <h2 class="ml-2">Reportes Generales sección Médica</h2>
<div class="row mt-4">
    <div class="col-lg-3 col-6">
      <!-- small box -->
      <div class="small-box bg-info">
        <div class="inner">
          <h4 class="text-center">Mascotas</h4>
        </div>
        <div class="icon">
          <i class="ion ion-bag"></i>
        </div>
        <a href="{% url 'reports:report_pet' %}" class="small-box-footer">Descargar <i class="fas fa-arrow-circle-right"></i></a>
      </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
      <!-- small box -->
      <div class="small-box bg-success">
        <div class="inner">
          <h4 class="text-center">Vacunas</h4>
        </div>
        <div class="icon">
          <i class="ion ion-bag"></i>
        </div>
        <a href="{% url 'reports:report_vaccine' %}" class="small-box-footer">Descargar <i class="fas fa-arrow-circle-right"></i></a>
      </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
      <!-- small box -->
      <div class="small-box bg-warning">
        <div class="inner">
          <h4 class="text-center">Desparasitacion</h4>
        </div>
        <div class="icon">
          <i class="ion ion-bag"></i>
        </div>
        <a href="{% url 'reports:report_parasite' %}" class="small-box-footer">Descargar <i class="fas fa-arrow-circle-right"></i></a>
      </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
      <!-- small box -->
      <div class="small-box bg-danger">
        <div class="inner">
          <h4 class="text-center">Consultas</h4>
        </div>
        <div class="icon">
          <i class="ion ion-bag"></i>
        </div>
        <a href="{% url 'reports:report_consultas' %}" class="small-box-footer">Descargar <i class="fas fa-arrow-circle-right"></i></a>
      </div>
    </div>
    <!-- ./col -->
    <div class="col-md-6">
      <div class="card card-danger">
          <div class="card-header">
              <h3 class="card-title">Reportes de consultas por rango de fecha</h3>
          </div>
          <div class="card-body">
              <!-- Date -->
              <div class="form-group">
                  <label>Rango de Fecha:</label>
                  <div class="input-group date" data-target-input="nearest">
                      <input type="text" name="date1" id="date1" class="form-control pull-right">
                      <div class="input-group-append" >
                          <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                      </div>
                  </div>
              </div>
          </div>
          <div class="modal-footer">
              <button type="submit"  id="btn-print" class="btn btn-primary">Generar</button>
            </div>
          <!-- /.card-body -->
      </div>
      <!-- /.card -->
  </div>
  </div>
</div>

{% endblock contenido %}
{% block pluginsjs %}
<script>

    function Change() {
        var input1 = document.getElementById('date1').value;

        lista_fecha = input1.split(' ');
        date1 = lista_fecha[0];
        date2 = lista_fecha[2];
        separador1 = date1.split('-');
        separador2 = date2.split('-');
        date1 = separador1[2] + '-' + separador1[1] + '-' + separador1[0];
        date2 = separador2[2] + '-' + separador2[1] + '-' + separador2[0];

        $("#btn-print").click(function (e){
            e.preventDefault();
            var f1, f2;
            f1= date1;
            f2= date2;
            var url = "/reports_dinamic/" + f1 + "/" + f2;
            window.open(url);
        });

    }

    $('#date1').change(function(){
        Change();
    });

    $(document).ready(function () {

        $('input[name="date1"]').daterangepicker({
            "locale": {
                "format": "DD-MM-YYYY",
                "separator": " - ",
                "applyLabel": "Aplicar",
                "cancelLabel": "Cancelar",
                "fromLabel": "De",
                "toLabel": "a",
                "customRangeLabel": "Custom",
                "daysOfWeek": [
                    "Do",
                    "Lu",
                    "Ma",
                    "Mi",
                    "Ju",
                    "Vi",
                    "Sa"
                ],
                "monthNames": [
                    "Enero",
                    "Febrero",
                    "Marzo",
                    "Abril",
                    "Mayo",
                    "Junio",
                    "Julio",
                    "Agosto",
                    "Septiembre",
                    "Octubre",
                    "Noviembre",
                    "Deciembre"
                ],
                "firstDay": 1
            }
        });
    });
</script>

<script src="{% static 'lib/plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'lib/plugins/daterangepicker/daterangepicker.js' %}"></script>
{% endblock pluginsjs %}

apps/reports/templates/health/parasite_reports.html
<!DOCTYPE html>
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<style>
    .head {
        text-align: center;
        text-transform: uppercase;
        font-size: 13px;
        font-weight: 600;
        margin-bottom: 3rem;
    }

    #invoice thead tr th {
        text-align: left;
        border-bottom: 1px solid black;
        border-top: 1px solid black;
        padding-top: 4px;
    }

    #invoice thead tr {
        margin-bottom: 0;
        padding-bottom: 0;
    }

    #invoice tbody tr {
        padding: 0;
    }

    .cosa{
        width: 100%;
        margin: 10px;
        border-top: black;
    }

    #invoice tbody tr td {
        text-align: left;
        border-bottom: 1px solid rgb(183, 183, 183);
        padding-top: 4px;
    }

</style>
<body>
<p class="head">
    <b style="font-size: 20px;">LEGOAGRO</b> <br>
</p>
<p>
    <b>FECHA DEL REPORTE:  {{ today|date:"d-m-Y" }}</b> <br>
    <b>Reporte de todas las desparasitaciones</b> <br>
</p>
<table id="invoice">
    <thead>
        <tr>
            <th class="cosa">Mascota</th>
            <th class="cosa">Cliente</th>
            <th class="cosa">Desparacitante</th>
            <th class="cosa">Descripcion</th>
            <th class="cosa">Proxima Fecha</th>
            <th class="cosa">Total</th>
        </tr>
    </thead>
    <tbody>
    {% for x in obj %}
        <tr>
            <td class="cosa">{{ x.pet.name }}</td>
            <td class="cosa">{{ x.pet.client }}</td>
            <td class="cosa">{{ x.name }}</td>
            <td class="cosa">{{ x.description }}</td>
            <td class="cosa">{{ x.date|date:"d-m-Y" }}</td>
            <td class="cosa">{{ x.total }}$</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>