CONFIG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('entity/', include('apps.entity.urls')),
    path('health/', include('apps.health.urls')),
    path('inventory/', include('apps.cashier.urls')),
    path('auth/', include('apps.usersys.urls')),
    path('', include('apps.dashboard.urls')),
    path('',include('apps.reports.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cashier/urls.py
from django.urls import path
from apps.cashier.views.product.views import ProductViews, detail_product
from apps.cashier.views.buy.views import BuyViews, Create_Buy, Edit_Buy
from apps.cashier.views.sale.views import SaleViews, Create_Sale, Edit_Sale


app_name = 'cashier'

urlpatterns = [
    path('listado_products/', ProductViews.as_view(), name='products'),
    path('listado_products/detail/<int:id>/', detail_product, name='product_detail'),
    path('listado_compras/', BuyViews.as_view(), name='buys'),
    path('registro_compra/', Create_Buy.as_view(), name='buy'),
    path('editar_compra/<int:pk>/', Edit_Buy.as_view(), name='buy_edit'),
    path('listado_ventas/', SaleViews.as_view(), name='sales'),
    path('registro_venta/', Create_Sale.as_view(), name='sale'),
    path('editar_venta/<int:pk>/', Edit_Sale.as_view(), name='sale_edit'),
    

]

apps/entity/urls.py
from django.urls import path
from apps.entity.views.client.views import ClientViews
from apps.entity.views.provider.views import ProviderViews
from apps.entity.views.pet.views import PetViews, detail_pet

app_name = 'entity'

urlpatterns = [
    # CRUD CLIENTS URL
    path('listado_clientes/', ClientViews.as_view(), name = 'clients'),
    # CRUD PROVIDERS URL
    path('listado_proveedores/', ProviderViews.as_view(), name = 'providers'),
    # CRUD PETS URL
    path('listado_mascotas/', PetViews.as_view(), name = 'pets'),
    # DETAIL PET URL
    path('listado_mascotas/detail/<int:id>/', detail_pet, name = 'detail_pet'),

]

apps/health/urls.py
from django.urls import path
from apps.health.views.consultas.views import ConsultaViews
from apps.health.views.desparacitacion.views import DesparacitacionViews 
from apps.health.views.vacunacion.views import VacunaViews
from apps.health.views.vaccine.views import VaccineDayViews, Create_VaccineDay, Edit_VaccineDay

app_name = 'health'

urlpatterns = [
    path("consultas/", ConsultaViews.as_view(), name="consultas"),
    path("desparacitacion/", DesparacitacionViews.as_view(), name="desparacitacion"),
    path("vacunacion/", VacunaViews.as_view(), name="vacunas"),
    # LIST, DETAIL AND DELETE VACCINE DAY
    path('listado_jornada_vacunacion/', VaccineDayViews.as_view(), name='vaccinedays'),
    # CREATE VACCINE DAY
    path('registrar_jornada_vacunacion/', Create_VaccineDay.as_view(), name='add_vaccineday'),
    # EDIT VACCINE DAY
    path('editar_jornada_vacunacion/<int:pk>/', Edit_VaccineDay.as_view(), name='edit_vaccineday'),
]

apps/reports/urls.py
from django.urls import path
from .views import PetsReports, VaccineReports, ParasiteReports, MenuHealth,MenuCashier, VentasReports, ConsultaReports
from .views import ConsultasReports, ProductosReports, ComprasReports, VentasDetalleReports, CompraDetalleReports, Report_RangeDate
from .views import Report_RangeDateVenta, Report_RangeDateCompra
from .views import ConsultaDetalleReports, VacunaDetalleReports, DespaDetalleReports

app_name = 'reports'

urlpatterns = [
    #MODULO HEALTH
    path("reports/pets/", PetsReports, name="report_pet"),
    path("reports/vaccine/", VaccineReports, name="report_vaccine"),
    path("reports/parasite/", ParasiteReports, name="report_parasite"),
    path("reports/consultation/<int:id>/", ConsultaReports, name="report_consultation"),
    path("reports/consultation/", ConsultasReports, name="report_consultas"),
    # MENU
    path("menu/reportes/medica/", MenuHealth.as_view(), name="menu_health"),
    path("menu/reportes/movimientos/", MenuCashier.as_view(), name="menu_cashier"),
    #MODULO CASHIER
    path("reports/ventas/", VentasReports, name="report_ventas"),
    path("reports/ventas/<int:id>/", VentasDetalleReports, name="report_ventasDetalle"),
    path("reports/compras/", ComprasReports, name="report_compras"),
    path("reports/compras/<int:id>/", CompraDetalleReports, name="report_CompraDetalle"),
    path("reports/productos/", ProductosReports, name="report_productos"),
    # REPORTES DINAMICOS
    path("reports_dinamic/<str:date1>/<str:date2>", Report_RangeDate, name="report_rangoConsulta"),
    path("reports_dinamic/venta/<str:date1>/<str:date2>", Report_RangeDateVenta, name="report_rangoVenta"),
    path("reports_dinamic/compra/<str:date1>/<str:date2>", Report_RangeDateCompra, name="report_rangoVenta"),

    # REPORTES DETALLES SECCION MEDICA
    path("reports/consultation/detalle/<int:id>/", ConsultaDetalleReports, name="report_consultationD"),
    path("reports/vacunacion/detalle/<int:id>/", VacunaDetalleReports, name="report_vaccinateD"),
    path("reports/desparasitacion/detalle/<int:id>/", DespaDetalleReports, name="report_desparasitationD"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  {% block tittle %}
  {% endblock tittle %}
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="{% static 'img/legoagro.jpg' %}" type="image/x-icon">
  {% block pluginscss %}
  {% endblock pluginscss %}

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'lib/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'lib/adminlte/css/adminlte.min.css' %}">
  <link rel="stylesheet" href="{% static 'lib/adminlte/css/styles.css' %}">
  <!-- Jquery Confirm css -->
  <link rel="stylesheet" href="{% static 'lib/plugins/jquery-confirm-v3/jquery-confirm.min.css' %}">
  <!-- Toastr js -->
  <link rel="stylesheet" href="{% static 'lib/plugins/toastr/toastr.min.css' %}">
  <!-- select2 js -->
  <link rel="stylesheet" href="{% static 'lib/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'lib/plugins/select2/css/select2.min.css' %}">

</head>

<body class="">
  <!-- Site wrapper -->
  <div class="wrapper">

    {% include "header_base.html" %}

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
        {% block contenido %}
        {% endblock contenido %}
    </div>

    <!-- ./wrapper -->

    {% include "footer.html" %}
  </div>
  
    <!-- jQuery -->
    <script src="{% static 'lib/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte/js/adminlte.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'lib/adminlte/js/demo.js' %}"></script>
    <!-- Jquery Confirm js -->
    <script src="{% static 'lib/plugins/jquery-confirm-v3/jquery-confirm.min.js' %}"></script>
    <!-- Codigo js para las paginas -->
    <script src="{% static 'js/codigoJS.js' %}"></script>
    <!-- Toastr js -->
    <script src="{% static 'lib/plugins/toastr/toastr.min.js' %}"></script>
    <!-- select2 js -->
    <script src="{% static 'lib/plugins/select2/js/select2.min.js' %}"></script>
    <script src="{% static 'lib/plugins/select2/js/i18n/es.js' %}"></script>

  
    {% block pluginsjs %}
    {% endblock pluginsjs %}

    {% block form.js %}
    {% endblock form.js %}
</body>

  <script>
    {% if messages %}
        {% for mensaje in messages %}
          {% if mensaje.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            function mensaje(sms) {
              toastr.error(sms)
            }
            mensaje('{{ mensaje }}')
          {% else %}
            function mensaje(sms) {
              toastr.success(sms)
            }
              mensaje('{{ mensaje }}')
          {% endif %}
        {% endfor %}
    {% endif %}
    

    {% block script %}   
    {% endblock script %}
  </script>

  {% block modal %}      
  {% endblock modal %}
</html>

templates/footer.html
{% load static %}
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
        <b>Version</b> 1.0
    </div>
    <strong>Copyright &copy; 2021 <a class="text-success" href="#">SISVET</a>.</strong> All rights
    reserved.
</footer>

templates/form.html
{% extends "base.html" %}
{% load static %}

{% block tittle %}
<title>{{ titulo }}</title>
{% endblock tittle %}

{% block contenido %}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item"><a href="{% url 'dashboard:dashboard' %}" class="text-success">SISVID</a>
                    </li>
                    <li class="breadcrumb-item"><a href="{{ list_url }}" class="text-success">{{ navegacion2 }}</a></li>
                    <li class="breadcrumb-item active">{{ navegacion }}</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>


<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <!-- form start -->
                {% block form %}
                {% endblock form %}
            </div>
        </div>
    </div>
</section>
<!-- /.card -->
{% endblock contenido %}


{% block script %}
<script>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}

                function ErrorForm(FormError) {
                    toastr.error(FormError)
                }
                ErrorForm('{{ error }}')
            {% endfor %}
        {% endfor %}
    {% endif %}


</script>
{% endblock script %}

{% block pluginsjs %}
    <script src="{% static 'lib/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <script src="{% static 'lib/plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'lib/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/plugins/bootstrap-touchspin-master/touchspin.min.js' %}"></script>
    <script src="{% static 'lib/plugins/moment/moment-with-locales.min.js' %}"></script>
    <script src="{% static 'lib/plugins/daterangepicker/daterangepicker.js' %}"></script>
{% endblock pluginsjs %}

{% block pluginscss %}
    <link rel="stylesheet" href="{% static 'lib/plugins/jquery-ui/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'lib/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'lib/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'lib/plugins/bootstrap-touchspin-master/touchspin.min.css' %}">
    <link rel="stylesheet" href="{% static 'lib/plugins/daterangepicker/daterangepicker.css' %}">
{% endblock pluginscss %}

templates/form_delete.html
{% extends "base.html" %}
{% load static %}
{% block tittle %}
<title>{{ titulo }}</title>
{% endblock tittle %}


{% block contenido %}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item"><a href="#" class="text-success">SISVID</a>
                    </li>
                    <li class="breadcrumb-item"><a href="#" class="text-success">#</a></li>
                    <li class="breadcrumb-item active">#</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-danger">
                    <div class="card-header color-nav">
                        <h3 class="card-title">#</h3>
                        <div class="card-tools">
                            <!-- Buttons, labels, and many other things can be placed here! -->
                            <!-- Here is a label for example -->
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    {% block form_delete %}
                    {% endblock form_delete %}
                </div>
            </div>
        </div>
</section>
{% endblock contenido %}

templates/header_base.html
{% load static %}
{% block header %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-success navbar-dark color-nav">

  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
  </ul>


  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">

    <li class="navbar-nav ml-auto mt-2 mr-2">
      <div class="time-label">
      </div>
    </li>

    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="modal" data-target="#modal-sm" href="#">
        <i class="fas fa-sign-out-alt"></i>
      </a>
    </li>

  </ul>
</nav>
<!-- /.navbar -->

<!-- Main Sidebar Container -->
<aside class="main-sidebar nav-compact sidebar-dark-primary elevation-4">


  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="{% static 'img/user.png' %}" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        <a href="#" class="d-block">{{request.user.username}}</a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->

        <li class="nav-item">
          <a href="{% url 'dashboard:dashboard' %}" class="nav-link">
            <i class="nav-icon fas fa-home"></i>
            <p>
              Inicio
            </p>
          </a>
        </li>
        
        {% if perms.usersys.view_notificationstatus %}
          <li class="nav-item">
            <a href="{% url 'dashboard:charts' %}" class="nav-link">
              <i class="nav-icon fas fa-chart-pie"></i>
              <p>
                Estadiscticas
              </p>
            </a>
          </li>
        {% endif %}

        <li class="nav-header">CARTERA DE CLIENTES</li>

        <li class="nav-item">
          <a href="{% url 'entity:clients' %}" class="nav-link">
            <i class="nav-icon fas fa-address-book"></i>
            <p>
              Clientes
            </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'entity:pets' %}" class="nav-link">
            <i class="nav-icon fas fa-paw"></i>
            <p>
              Mascotas
            </p>
          </a>
        </li>

        <li class="nav-item">
          <a href="{% url 'entity:providers' %}" class="nav-link">
            <i class="nav-icon fas fa-truck-loading"></i>
            <p>
              Proveedores
            </p>
          </a>
        </li>

        <li class="nav-header">SECCIÓN MEDICA</li>

        <li class="nav-item has-treeview">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-book-medical"></i>
            <p>
              Registro Medico
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'health:consultas' %}" class="nav-link">
                <i class="fas fa-comment-medical nav-icon"></i>
                <p>Consulta</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'health:vacunas' %}" class="nav-link">
                <i class="fas fa-syringe nav-icon"></i>
                <p>Vacunacion</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'health:desparacitacion' %}" class="nav-link">
                <i class="fas fa-bug nav-icon"></i>
                <p>Desparasitacion</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'health:vaccinedays' %}" class="nav-link">
                <i class="fas fa-briefcase-medical nav-icon"></i>
                <p>Jornada de Vacunación</p>
              </a>
            </li>

          </ul>
        </li>
        <li class="nav-header">MOVIMIENTOS</li>


        <li class="nav-item has-treeview">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-store-alt"></i>
            <p>
              Tienda
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'cashier:products' %}" class="nav-link">
                <i class="fas fa-box nav-icon"></i>
                <p>
                  Productos
                </p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'cashier:buys' %}" class="nav-link">
                <i class="nav-icon fas fa-shopping-cart"></i>
                <p>
                  Compra
                </p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'cashier:sales' %}" class="nav-link">
                <i class="nav-icon fas fa-cash-register"></i>
                <p>
                  Ventas
                </p>
              </a>
            </li>
          </ul>
        </li>

        <li class="nav-header">SALIDAS</li>

        <li class="nav-item has-treeview">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-file-pdf"></i>
            <p>
              Reportes
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'reports:menu_health' %}" class="nav-link">
                <i class="far fa-file-pdf nav-icon"></i>
                <p>Seccion Medica</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'reports:menu_cashier' %}" class="nav-link">
                <i class="far fa-file-pdf nav-icon"></i>
                <p>Seccion Movimientos</p>
              </a>
            </li>
            
          </ul>
        </li>

<<<<<<< HEAD
        
        {% if perms.usersys.view_notificationstatus %}
          <li class="nav-header">SISTEMA</li>

          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-cogs"></i>
              <p>
                Configuración
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'usersys:menu_noti' %}" class="nav-link">
                  <i class="fas fa-envelope nav-icon"></i>
                  <p>
                    Notificaciones
                  </p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'usersys:menu_backup' %}" class="nav-link">
                  <i class="nav-icon fas fa-save"></i>
                  <p>
                    Respaldo de Datos
                  </p>
                </a>
              </li>
            </ul>
          </li>       
        {% endif %}
      
=======

        <li class="nav-header">SISTEMA</li>


        <li class="nav-item has-treeview">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-cogs"></i>
            <p>
              Configuración
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'usersys:menu_noti' %}" class="nav-link">
                <i class="fas fa-envelope nav-icon"></i>
                <p>
                  Notificaciones
                </p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'usersys:menu_backup' %}" class="nav-link">
                <i class="nav-icon fas fa-save"></i>
                <p>
                  Respaldo de Datos
                </p>
              </a>
            </li>
          </ul>
        </li>
>>>>>>> b0891a40af8565bd3fc0e1b635d55a867dbce1e5

      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>

<div class="modal fade" id="modal-sm">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Salir</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>¿Esta seguro de salir <small class="badge badge-success">{{request.user.username}}</small>?</p>
      </div>
      <div class="modal-footer justify-content-between">
        <button type="button" class="btn btn-dark" data-dismiss="modal">Cancelar</button>
        <a type="button" class="btn btn-success btn-colores" href='{% url "usersys:logout" %}'>Si, Salir</a>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
{% endblock header %}

templates/list.html
{% extends "base.html" %}
{% load static %}

{% block pluginscss %}
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'lib/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'lib/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
{% endblock pluginscss %}

{% block tittle %}
<title>{{ titulo }}</title>
{% endblock tittle %}

{% block contenido %}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item"><a href="{% url 'dashboard:dashboard' %}" class="text-success">SISVET</a></li>
                    <li class="breadcrumb-item">{{ navegacion }}</li>
                    <li class="breadcrumb-item active">Listado</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <!-- /.card -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title"><i class="fas fa-list-ul"></i> {{ sub_titulo }}</h3>

                        <div class="card-tools">
                            <!-- tools en la derecha -->
                            {% block add_element %}
                            {% endblock add_element %}
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="data" class="table table-bordered table-striped">
                            <thead>
                                {% block t_body %}
                                {% endblock t_body %}
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </div>
</section>
{% endblock contenido %}


{% block pluginsjs %}
<!-- DataTables -->
<script src="{% static 'lib/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'lib/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'lib/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'lib/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
{% block head_list %}

{% endblock %}
{% endblock pluginsjs %}