CONFIG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('entity/', include('apps.entity.urls')),
    path('health/', include('apps.health.urls')),
    path('inventory/', include('apps.cashier.urls')),
    path('auth/', include('apps.usersys.urls')),
    path('', include('apps.dashboard.urls')),
    path('',include('apps.reports.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/health/urls.py
from django.urls import path
from apps.health.views.consultas.views import ConsultaViews
from apps.health.views.desparacitacion.views import DesparacitacionViews 
from apps.health.views.vacunacion.views import VacunaViews
from apps.health.views.vaccine.views import VaccineDayViews, Create_VaccineDay, Edit_VaccineDay

app_name = 'health'

urlpatterns = [
    path("consultas/", ConsultaViews.as_view(), name="consultas"),
    path("desparacitacion/", DesparacitacionViews.as_view(), name="desparacitacion"),
    path("vacunacion/", VacunaViews.as_view(), name="vacunas"),
    # LIST, DETAIL AND DELETE VACCINE DAY
    path('listado_jornada_vacunacion/', VaccineDayViews.as_view(), name='vaccinedays'),
    # CREATE VACCINE DAY
    path('registrar_jornada_vacunacion/', Create_VaccineDay.as_view(), name='add_vaccineday'),
    # EDIT VACCINE DAY
    path('editar_jornada_vacunacion/<int:pk>/', Edit_VaccineDay.as_view(), name='edit_vaccineday'),
]

apps/entity/models.py
from django.db import models
from CONFIG.settings import MEDIA_URL
from datetime import datetime, date
from django.forms import model_to_dict
from apps.entity.choices import type_client, gender_choices, gender_pet, species_pet

import secrets

# Create your models here.

def my_urlsecret():
    return secrets.token_urlsafe(32)

class Estado(models.Model):
    status = models.BooleanField(default=True, verbose_name='Estado')
    urlsecret = models.SlugField(max_length=50, default=my_urlsecret , null=True , blank=True)
    next_visit = models.DateField(default=date.today, verbose_name='Proxima visita', null=True , blank=True)
    status_notify = models.BooleanField(default=True, verbose_name='Notificador')

    class Meta:
        abstract=True

class Client(Estado):
    dni = models.CharField(max_length=8, verbose_name='Cedula', unique=True)
    gender = models.CharField(max_length=15, choices=gender_choices )
    type_name = models.CharField(max_length=10, choices=type_client, default = 'V-')
    first_name = models.CharField(verbose_name="Nombres", max_length=40)
    last_name = models.CharField(verbose_name="Apellidos", max_length=40)
    address = models.CharField(verbose_name="Direccion Habitacional", max_length=100, null=True, blank=True)
    mobile = models.CharField(verbose_name="Número de Celular",  max_length=11 , null = True, blank=True)
    tlf = models.CharField(verbose_name="Número de Telefonico", max_length=11 , null = True, blank=True)
    Email = models.EmailField(verbose_name= "Correo Electronico", null = True, blank=True)
    fechaa = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de edición")

    def __str__(self):
        return (self.dni + ' : ' + self.first_name)

    def get_gender_display(self):
        if self.gender:
            return '{}'.format(self.gender)
    

    def toJSON(self):
        item = model_to_dict(self)
        item['gender'] = self.get_gender_display()
        return item

    class Meta:
        verbose_name_plural = 'Clientes'
        verbose_name = 'Cliente'
        ordering = ['id']

class Provider(Estado):
    name = models.CharField(verbose_name="Nombres", max_length=40)
    rif = models.CharField(max_length =100, unique =True, verbose_name='RIF', null = True, blank=True)
    mobile = models.CharField(verbose_name="Número de Celular",  max_length=11 , null = True, blank=True)
    tlf = models.CharField(verbose_name="Número de Telefonico", max_length=11 , null = True, blank=True)
    Email = models.EmailField(verbose_name= "Correo Electronico", null = True, blank=True)
    date = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de edición")

    def __str__(self):
        return (self.name)

    def toJSON(self):
        item = model_to_dict(self)
        return item

    class Meta:
        verbose_name_plural = 'Proveedores'
        verbose_name = 'Proveedor'
        ordering = ['id']

class Pet(Estado):
    name = models.CharField(max_length = 50, verbose_name='Nombre')
    date_nac = models.DateField(auto_now=False, auto_now_add=False, verbose_name='Fecha de Nacimiento')
    gender = models.CharField(max_length = 20, choices=gender_pet, default='Hembra')
    race = models.CharField(max_length = 50, verbose_name='Raza')
    weight = models.FloatField(max_length = 10, verbose_name='Peso', default=0)
    specie = models.CharField(max_length = 50, choices=species_pet, default='Gato')
    date_up = models.DateField(auto_now=False, verbose_name='Fecha visita')
    substitute = models.CharField(max_length = 150, verbose_name='Suplente', null = True, blank=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='Propietario')

    def __str__(self):
        return (self.name)


    def toJSON(self):
        item = model_to_dict(self)
        item['client'] = {'id':self.client.id, 'dni': self.client.dni}
        return item

    class Meta:
        verbose_name_plural = 'Mascotas'
        verbose_name = 'Mascota'
        ordering = ['id']   
    
    

apps/health/models.py
from django.db import models
from CONFIG.settings import MEDIA_URL
from datetime import datetime
from django.forms import model_to_dict
from django.db.models.signals import post_save, pre_save
from datetime import datetime, date, time, timedelta
import calendar
# Create your models here.
from apps.entity.models import my_urlsecret, Estado, Pet


class Consultation(Estado):
    motive = models.TextField(verbose_name='Motivo')
    symptom = models.TextField(verbose_name='Sintomas')
    temperature = models.TextField( verbose_name='Temperatura')
    total = models.FloatField(null = True, blank=True,verbose_name='Total')
    date_c = models.DateField(default= date.today, verbose_name='Fecha Creacion')
    date_u = models.DateField(null=True, blank= True, verbose_name='Fecha Actualizacion')
    diag_pre = models.TextField(null = True, blank=True, verbose_name='Diagnostico preventivo')
    diag_def = models.TextField(null = True, blank=True, verbose_name='Diagnostico definitivo')
    fre_car = models.TextField( null = True, blank=True, verbose_name='Frecuencia cardiaca')
    fre_res = models.TextField( null = True, blank=True, verbose_name='Frecuencia respiratoria')
    examination = models.TextField(null = True, blank=True, verbose_name='Examen')
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE, verbose_name='Paciente')
    
    def __str__(self): 
        return (self.pet.name)

    def toJSON(self):
        item = model_to_dict(self)
        item['pet'] = {'name': self.pet.name,'id': self.pet.id , 'client': self.pet.client.dni, 'gender': self.pet.gender, 'race': self.pet.race, 'specie': self.pet.specie}
        return item

    class Meta:
        verbose_name_plural = 'Consultas'
        verbose_name = 'Consulta'
        ordering = ['id']   


class Vaccine(Estado):
    name = models.TextField(max_length = 50, verbose_name='Vacuna')
    description = models.TextField(verbose_name='Vacuna', null=True, blank=True)
    total = models.FloatField(default=0, verbose_name='Total')
    date = models.DateField(auto_now=False, auto_now_add=False, verbose_name='Fecha Creacion')
    new_date = models.DateField(verbose_name='proxima cita',null = True, blank=True )
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE, verbose_name='Paciente')

    def __str__(self):
        return (self.name)

    def toJSON(self):
        item = model_to_dict(self)
        item['pet'] = {'name': self.pet.name,'id': self.pet.id , 'client': self.pet.client.dni, 'gender': self.pet.gender, 'race': self.pet.race, 'specie': self.pet.specie, 'new_date':self.new_date}
        return item

    class Meta:
        verbose_name_plural = 'Vacunaciones'
        verbose_name = 'Vacunacion'
        ordering = ['id']   


class Parasite(Estado):
    name = models.TextField(verbose_name='Desparasitante')
    description = models.TextField(verbose_name='Desparasitante', null=True, blank=True)
    total = models.FloatField(default=0, verbose_name='Total')
    date = models.DateField(auto_now_add=False, verbose_name='Fecha Creacion')
    new_date = models.DateField(verbose_name='Proxima cita', null = True, blank=True)
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE, verbose_name='Paciente')    

    def __str__(self):
        return (self.name)

    def toJSON(self):
        item = model_to_dict(self)
        item['pet'] = {'name': self.pet.name,'id': self.pet.id , 'client': self.pet.client.dni, 'gender': self.pet.gender, 'race': self.pet.race, 'specie': self.pet.specie, 'new_date':self.new_date}
        return item

    class Meta:
        verbose_name_plural = 'Desparasitaciones'
        verbose_name = 'Desparasitacion'
        ordering = ['id']    
    

apps/health/forms.py
from django.forms import ModelForm
from apps.health.models import Consultation, Vaccine, Parasite

class ConsultaForm(ModelForm):

    class Meta:
        model = Consultation
        fields = '__all__'

class DesparacitacionForm(ModelForm):

    class Meta:
        model = Parasite
        fields = '__all__'

class VacunaForm(ModelForm):

    class Meta:
        model = Vaccine
        fields = '__all__'

apps/health/views/consultas/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, Http404
from django.http import JsonResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from datetime import datetime, date, time, timedelta
from django.contrib.auth.models import User, Permission

from apps.health.forms import ConsultaForm
from apps.health.models import Consultation
from apps.entity.models import Pet
from apps.entity.mixins import Perms_Check

# CRUD CLIENTS URL
class ConsultaViews(Perms_Check, TemplateView):
    template_name = 'consultas/consultas.html'
    permission_required = 'health.view_consultation'

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for i in Consultation.objects.all():
                    if i.status == True:
                        i.status = '<span class="badge badge-success btn-colores">Activado</span>'
                    else:
                        i.status = '<span class="badge badge-dark">Desactivado</span>'
                    data.append(i.toJSON())
            
            elif action == 'add':
                perms = ('health.add_consultation',)
                if request.user.has_perms(perms):
                    consul = Consultation()
                    consul.motive = request.POST.get('motive')
                    consul.symptom = request.POST.get('symptom')
                    consul.temperature = request.POST.get('temperature')
                    consul.total = request.POST.get('total')
                    consul.date_c = request.POST.get('date_c')
                    consul.date_u = request.POST.get('date_u')
                    consul.diag_pre = request.POST.get('diag_pre')
                    consul.diag_def = request.POST.get('diag_def')
                    consul.fre_car = request.POST.get('fre_car')
                    consul.fre_res = request.POST.get('fre_res')
                    consul.examination = request.POST.get('examination')
                    consul.pet = Pet.objects.get(pk = request.POST.get('pet'))
                    consul.status = 'status' in request.POST
                    consul.save()
                    
                else:
                    data['error'] = 'No tiene permisos para registrar una consulta'
            
            elif action == 'edit':
                perms = ('health.change_consultation',)
                if request.user.has_perms(perms):
                    consul = Consultation.objects.get(pk=request.POST['id'])
                    consul.motive = request.POST.get('motive')
                    consul.symptom = request.POST.get('symptom')
                    consul.temperature = request.POST.get('temperature')
                    consul.total = request.POST.get('total')
                    consul.date_c = request.POST.get('date_c')
                    consul.date_u = request.POST.get('date_u')
                    consul.diag_pre = request.POST.get('diag_pre')
                    consul.diag_def = request.POST.get('diag_def')
                    consul.fre_car = request.POST.get('fre_car')
                    consul.fre_res = request.POST.get('fre_res')
                    consul.examination = request.POST.get('examination')
                    consul.pet = Pet.objects.get(pk=request.POST.get('pet'))
                    consul.status = 'status' in request.POST
                    consul.save()

                else:
                    data['error'] = 'No tiene permisos para editar una consulta'      

            elif action == 'delete':
                perms = ('health.delete_consultation',)
                if request.user.has_perms(perms):
                    consul = Consultation.objects.get(pk=request.POST['id'])            
                    consul.delete()
                else:
                    data['error'] = 'No tiene permisos para eliminar una consulta'

            else:
                data['error'] = 'Ha ocurrido un error'           

        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'SISVET | Listado de Consultas'
        context['sub_titulo'] = 'Listado de Consultas'
        context['navegacion'] = 'Consultas'
        context['form'] = ConsultaForm()
        context['list_url'] = reverse_lazy('health:consultas')
        return context

apps/health/templates/desparacitacion/desparacitacion.html
{% extends "list.html" %}
{% load static %}
{% load widget_tweaks %}
{% block head_list %}
  <script src="{% static 'desparacitacion/list.js' %}"> </script>
{% endblock %}
 
{% block add_element %}
<a href="#" class="btn btn-colores btn-add"><i class="fas fa-plus-square"></i></a>
{% endblock add_element %}
 
{% block t_body %}
    <tr>
        <th scope="col" >Mascota</th>
        <th scope="col" >Cliente</th>
        <th scope="col" >Desparasitante</th>
        <th scope="col" >Descripcion</th>
        <th scope="col" >Fecha</th>
        <th scope="col" >Monto a Pagar</th>
        <th scope="col" >Estado</th>
        <th scope="col" >Opciones</th>
    </tr>
{% endblock t_body %}

{% block modal %}
<!-- Modal -->
<div class="modal fade" id="ModalNew" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <form method="POST" action="">
        {% csrf_token %}
        <input type="hidden" name="action" value="add" id="status">
        <input type="hidden" name="id" id="id" value="0">

        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header color-nav">
                <h5 class="modal-title" id="exampleModalLabel">Registrar Desparacitacion</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="card-body">
                    <div class="form-group">
                        <div class="row">
                        <div class="col">
                            <label for="id_pet">Mascota <span class="text-danger" title="Campo Obligatorio">*</span></label>
                            {{ form.pet|add_class:'form-control'|attr:'name:pet'|add_class:'select2'|attr:'style:width:100%'}}
                        </div>
                        </div>
                        <div class="row">
                        <div class="col">
                            <label for="id_name">Desparacitante <span class="text-danger" title="Campo Obligatorio">*</span></label>
                            {{ form.name|add_class:'form-control'|attr:'name:name'|attr:'placeholder:Desparacitante'|attr:'style:resize:none'|attr:'rows:3' }}
                        </div>
                        <div class="col">
                            <label for="id_description">Descripcion <span class="text-danger" title="Campo Obligatorio">*</span></label>
                            {{ form.description|add_class:'form-control'|attr:'name:description'|attr:'style:resize:none'|attr:'rows:3'}}
                        </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col">
                                <label for="id_date">Fecha <span class="text-danger" title="Campo Obligatorio">*</span></label>
                                {{ form.date|add_class:'form-control'|attr:'name:date'|attr:'type:date'}}
                            </div>
                        <div class="col">
                            <label for="id_total">Monto a Pagar <span class="text-danger" title="Campo Obligatorio">*</span></label>
                            {{ form.total|add_class:'form-control'|attr:'name:total'}}
                        </div>
                    <div class="custom-control custom-switch custom-switch-on-success custom-switch-off-white" style="display: none;">
                        {{ form.status|add_class:'custom-control-input'|attr:'name:status'|add_class:'status'}}
                        <label class="custom-control-label" for="id_status" >Estado <span class="text-danger" title="Campo Obligatorio">*</span></label>
                    </div>
                    
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-dark" data-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-success btn-colores">Guardar</button>
            </div>
            </div>
        </div>
        </div>
        </div>
  </form>
</div>

<div class="modal fade" id="Modal_Detail" style="display: none;" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-4">

            <!-- Profile Image -->
            <div class="card card-success card-outline">
              <div class="card-body box-profile">
                <div class="text-center">
                  <img class="profile-user-img img-fluid img-circle" id="detail-img" src="{% static 'img/bone.png' %}" alt="User profile picture">
                </div> 
  
                <h3 id="detail-name1" class="profile-username text-center"></h3>
    
                <ul class="list-group list-group-unbordered mb-3">
                  <li class="list-group-item">
                    <b><i class="fas fa-transgender mr-1"></i> Genero</b> <a id="detail-gender" class="float-right"></a>
                  </li>
                  <li class="list-group-item">
                    <b><i class="fas fa-dog mr-1"></i> Especie</b> <a id="detail-specie" class="float-right"></a>
                  </li>
                  <li class="list-group-item">
                    <b><i class="fas fa-paw mr-1"></i> Raza</b> <a id="detail-race" class="float-right"></a>
                  </li>
                </ul>
                <div class="justify-content-between">
                  <div class="row">
                    <div class="col">
                      <a href="#" rel="edit" class="btn btn-warning"><i class="fas fa-edit"></i></a>
                    </div>
                    <div class="col">
                      <a href="#" rel="delete" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a>
                    </div>
                </div>

                </div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
  
           
          </div>
          <div class="col">
             <!-- About Me Box -->
             <div class="card card-success">
              <div class="card-header">
                <h3 id="detail-name2" class="card-title"></h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <strong><i class="fas fa-user mr-1 "></i> Desparacitante</strong>
  
                <p class="text-muted" id='detail-client'>
                </p>
  
                <hr>

                <strong><i class="fas fa-users mr-1 "></i> Descripcion</strong>
  
                <p class="text-muted" id='detail-substitute'>
                </p>
  
                <hr>
                <strong><i class="fas fa-diagnoses mr-1"></i>Fecha</strong>
  
                <p id="detail-date_up" class="text-muted"></p>
  
                <hr>
                <strong><i class="fas fa-diagnoses mr-1"></i>Proxima cita</strong>
  
                <p id="detail-new_data" class="text-muted"></p>
                <hr>
  
                <strong><i class="fas fa-calendar-check mr-1"></i> Monto a Pagar</strong>
                <p id="detail-diag_def" class="text-muted"></p>

                <p id="detail-weight" class="text-muted">
                <p id="detail-id" hidden class="text-muted">

                </p>
                
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-dark" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
{% endblock modal %}